### ISSUE TITLE
run_train_bert_ie.py seems to be not working

### ISSUE THREAD

**Issue by 1063451124** [zerohd4869/DialogueCRN#6]
Hi, I have been interested in your work recently, and I am trying to run it. One thing I noticed is that the readme is different from the code when referring to the use of bash in the following part. Does it seem that the bash is trying to use run_train_ie.py to read iemocap_features_roberta.pkl? Could you give more details about it, please? Thanks a lot!
![image](https://user-images.githubusercontent.com/20579776/227704824-3a2cdd48-9417-404f-b332-af191f740c88.png)
![image](https://user-images.githubusercontent.com/20579776/227704864-73c5be93-5560-4254-8e7f-0ed9a68fc980.png)

And the result log seems to show the python code ie and bert_ie can neither run with roberta iemocap dataset.
![image](https://user-images.githubusercontent.com/20579776/227705218-fe79c0e6-808f-45e6-aee3-d5108654ee8a.png)
![image](https://user-images.githubusercontent.com/20579776/227705285-19950452-fa39-40f9-b130-4b8aea931b49.png)

**Comment by zerohd4869** [comment]
> Hi, I have been interested in your work recently, and I am trying to run it. One thing I noticed is that the readme is different from the code when referring to the use of bash in the following part. Does it seem that the bash is trying to use run_train_ie.py to read iemocap_features_roberta.pkl? Could you give more details about it, please? Thanks a lot! ![image](https://user-images.githubusercontent.com/20579776/227704824-3a2cdd48-9417-404f-b332-af191f740c88.png) ![image](https://user-images.githubusercontent.com/20579776/227704864-73c5be93-5560-4254-8e7f-0ed9a68fc980.png)
> 
> And the result log seems to show the python code ie and bert_ie can neither run with roberta iemocap dataset. ![image](https://user-images.githubusercontent.com/20579776/227705218-fe79c0e6-808f-45e6-aee3-d5108654ee8a.png) ![image](https://user-images.githubusercontent.com/20579776/227705285-19950452-fa39-40f9-b130-4b8aea931b49.png)

Thank you for your interest. 
In the first image, it seems that there is no problem with the run_train_bert_ie.py script. You may need to update the current version of the files you are running, especially dataloader.py and run_train_bert_ie.py in the repo, and then try running the code again. (The old version of the repo was based on Glove scripts, and the new version based on RoBERTa is being gradually updated recently.) 
The error in the second image is most likely caused by running the Glove version of the py file after loading the RoBERTa embedding. Please refer to the example of running the py file in the README.md for more details. 
If there are still issues, please feel free to contact me.

**Comment by zerohd4869** [comment]
Thank you for your interest.
In the first image, it seems that there is no problem with the run_train_bert_ie.py script. You may need to update the current version of the files you are running, especially dataloader.py and run_train_bert_ie.py in the repo, and then try running the code again. (The old version of the repo was based on Glove scripts, and the new version based on RoBERTa is being gradually updated recently.)
The error in the second image is most likely caused by running the Glove version of the py file after loading the RoBERTa embedding. Please refer to the example of running the py file in the README.md for more details.
If there are still issues, please feel free to contact me.
